# 實驗名稱
experiment_name: "default_experiment"

# 模型配置
model:
  name: "distilbert-base-uncased"
  num_labels: 2

# LoRA 配置
lora:
  r: 8
  lora_alpha: 16
  target_modules: ["q_lin", "v_lin"]
  lora_dropout: 0.1
  bias: "none"
  task_type: "SEQ_CLS"

# 資料配置
data:
  dataset_name: "glue"
  dataset_config: "sst2"
  train_samples: 500
  eval_samples: 100
  max_length: 128
  validation_rules:
    min_text_length: 5
    max_text_length: 500
    allow_empty: false
    remove_html: true

# 訓練配置
training:
  output_dir: "./results"
  eval_strategy: "epoch"
  learning_rate: 5.0e-4
  per_device_train_batch_size: 2
  num_train_epochs: 1
  logging_steps: 10
  device: null  # 自動檢測

# 系統配置
system:
  log_file: "logs/training_progress.log"
  save_config: true