namespace: lora-system

global:
  imagePullPolicy: IfNotPresent

storage:
  enabled: false

storageHostPath: /mnt/data/finetune-results

config:
  name: lora-config
  data:
    CELERY_BROKER_URL: "redis://finetune-platform-redis.lora-system.svc.cluster.local:6379/0"
    CELERY_RESULT_BACKEND: "redis://finetune-platform-redis.lora-system.svc.cluster.local:6379/1"
    API_URL: "http://finetune-platform-api.lora-system.svc.cluster.local:8000"
    API_HOST: "0.0.0.0"
    API_PORT: "8000"
    REDIS_HOST: "finetune-platform-redis.lora-system.svc.cluster.local"
    REDIS_PORT: "6379"
    REDIS_URL: "redis://finetune-platform-redis.lora-system.svc.cluster.local:6379"
    UI_PORT: "8501"
    PYTHONPATH: "/app"
    PYTHONUNBUFFERED: "1"
    TZ: "Asia/Taipei"

secrets:
  name: lora-secrets
  jwtSecret: change-me

api:
  image:
    repository: finetune-app
    tag: latest
  replicas: 1
  service:
    type: NodePort
    port: 8000
    nodePort: 30080
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2
      memory: 2Gi

worker:
  image:
    repository: finetune-app
    tag: latest
  replicas: 1
  volumeClaim: results-pvc
  service:
    type: ClusterIP
    port: 5555
    nodePort: null
    name: worker
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2
      memory: 2Gi

workerPools:
  - name: tenant-admin
    namespace: tenant-admin
    createNamespace: true
    replicas: 1
    image:
      repository: finetune-app
      tag: latest
    volumeClaim: tenant-admin-results-pvc
    volumeName: tenant-admin-results-pv
    quota:
      enabled: true
      name: tenant-admin-quota
      hard:
        pods: "10"
        requests.cpu: "4"
        requests.memory: "8Gi"
  - name: tenant-user
    namespace: tenant-user
    createNamespace: true
    replicas: 2
    image:
      repository: finetune-app
      tag: latest
    volumeClaim: tenant-user-results-pvc
    volumeName: tenant-user-results-pv
    quota:
      enabled: true
      name: tenant-user-quota
      hard:
        pods: "3"
        requests.cpu: "1"
        requests.memory: "2Gi"

redis:
  image:
    repository: redis
    tag: latest
  replicas: 1
  hostPath: /mnt/data/finetune-results/redis
  service:
    type: ClusterIP
    port: 6379
    nodePort: null
    name: redis
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1Gi

ui:
  image:
    repository: finetune-app
    tag: latest
  replicas: 1
  service:
    type: NodePort
    port: 8501
    nodePort: 30501
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2
      memory: 2Gi

prometheus:
  enabled: true
  image:
    repository: prom/prometheus
    tag: latest
  service:
    type: ClusterIP
    port: 9090
    nodePort: null
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1Gi

grafana:
  enabled: true
  image:
    repository: grafana/grafana
    tag: latest
  adminUser: admin
  adminPassword: admin
  service:
    type: NodePort
    port: 3000
    nodePort: 30300
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1Gi
