{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "finetune-platform.fullname" . }}-grafana-config
  namespace: {{ .Values.namespace | default "lora-system" }}
  labels:
    {{- include "finetune-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
    monitoring: "true"
data:
  datasource.yml: |-
{{ tpl ((.Files.Get "files/grafana-datasource.yml")) . | indent 4 }}
  dashboard.yml: |-
{{ tpl ((.Files.Get "files/grafana-dashboard-provider.yml")) . | indent 4 }}
  dashboard.json: |-
{{ (.Files.Get "files/grafana-dashboard.json") | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "finetune-platform.fullname" . }}-grafana
  namespace: {{ .Values.namespace | default "lora-system" }}
  labels:
    {{- include "finetune-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "finetune-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: grafana
  template:
    metadata:
      labels:
        {{- include "finetune-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: grafana
    spec:
      containers:
        - name: grafana
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.grafana.service.port }}
              name: http
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.adminUser | quote }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.adminPassword | quote }}
            - name: GF_PATHS_PROVISIONING
              value: /etc/grafana/provisioning
          volumeMounts:
            - name: grafana-config
              mountPath: /etc/grafana/provisioning/datasources/datasource.yml
              subPath: datasource.yml
            - name: grafana-config
              mountPath: /etc/grafana/provisioning/dashboards/dashboard.yml
              subPath: dashboard.yml
            - name: grafana-config
              mountPath: /etc/grafana/dashboards/dashboard.json
              subPath: dashboard.json
          resources:
            {{- toYaml .Values.grafana.resources | nindent 12 }}
      volumes:
        - name: grafana-config
          configMap:
            name: {{ include "finetune-platform.fullname" . }}-grafana-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "finetune-platform.fullname" . }}-grafana
  namespace: {{ .Values.namespace | default "lora-system" }}
  labels:
    {{- include "finetune-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  selector:
    {{- include "finetune-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
  ports:
    - name: http
      port: {{ .Values.grafana.service.port }}
      targetPort: {{ .Values.grafana.service.port }}
      protocol: TCP
{{- if and (eq .Values.grafana.service.type "NodePort") .Values.grafana.service.nodePort }}
      nodePort: {{ .Values.grafana.service.nodePort }}
{{- end }}
{{- end }}
