{{- $root := . -}}
{{- $namespaces := list (include "finetune-platform.controlNamespace" $root) -}}
{{- range $pool := .Values.workerPools }}
  {{- with $pool.namespace }}
    {{- $namespaces = append $namespaces . -}}
  {{- end }}
{{- end }}
{{- $namespaces = uniq $namespaces -}}
{{- $first := true -}}
{{- range $ns := $namespaces }}
{{- if not $first }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $root.Values.secrets.name }}
  namespace: {{ $ns }}
type: Opaque
stringData:
  JWT_SECRET: {{ $root.Values.secrets.jwtSecret | quote }}
{{- $first = false -}}
{{- end }}
