apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: Prometheus
    url: http://{{ include "finetune-platform.fullname" . }}-prometheus:{{ .Values.prometheus.service.port }}
    isDefault: true
    editable: false
