global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets:
          - {{ include "finetune-platform.fullname" . }}-api:{{ .Values.api.service.port }}
