apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: lora-system
  labels:
    app: prometheus
    component: monitoring
    app.kubernetes.io/name: finetune-platform
  
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "fastapi"
        metrics_path: /metrics
        static_configs:
          - targets:
              - api:8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: lora-system
  labels:
    app: prometheus
    component: monitoring
    app.kubernetes.io/name: finetune-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      component: monitoring
  template:
    metadata:
      labels:
        app: prometheus
        component: monitoring
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
          ports:
            - containerPort: 9090
              name: http
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: data
              mountPath: /prometheus
      volumes:
        - name: config
          configMap:
            name: prometheus-config
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: lora-system
  labels:
    app: prometheus
    component: monitoring
    app.kubernetes.io/name: finetune-platform
spec:
  type: ClusterIP
  selector:
    app: prometheus
    component: monitoring
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP
