apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: results-pvc
  namespace: lora-system
  labels:
    app: finetune-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard  # minikube 預設的 storage class
