apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: lora-system
  labels:
    app: redis
    component: cache
spec:
  replicas: {{ .Values.redis.replicas | default 1 }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        component: cache
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: {{ .Values.redis.service.port | default 6379 }}
          name: redis
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: redis-data
          mountPath: /data
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: results-pvc
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: lora-system
  labels:
    app: redis
    component: cache
spec:
  type: {{ .Values.redis.service.type | default "ClusterIP" }}
  ports:
  - port: {{ .Values.redis.service.port | default 6379 }}
    targetPort: {{ .Values.redis.service.port | default 6379 }}
    protocol: TCP
    name: redis
  selector:
    app: redis
